instructor/courseAdd.php
instructor/lib/rosterFunctions.php
instructor/lib/termPresentation.php
instructor/surveys.php
instructor/updateRoster.php

Update code to allow roster updates

Created code to enable updating the roster

---

instructor/lib/enrollmentFunctions.php
instructor/rosterUpdate.php
instructor/surveys.php

Code completed and tested which can expand or replace a course's roster.

CourseRosterExpansion

---

instructor/lib/enrollmentFunctions.php
instructor/rosterConfirm.php

Improved reporting of students on the roster and not in the file.

RosterConfirmation

---

db_creation_files/onboarding_script.sql
fake_shibboleth.php
index.php
instructor/lib/enrollmentFunctions.php
instructor/lib/fileParse.php
instructor/lib/pairingFunctions.php
instructor/lib/rubricQueries.php
instructor/lib/surveyQueries.php
instructor/rosterConfirm.php
instructor/rubricReview.php
instructor/surveyAdd.php
instructor/surveyConfirm.php
instructor/surveyDuplicate.php
instructor/surveyUpdate.php
lib/studentQueries.php

Confirmation page done & dusted.

SurveyConfirmationPage

---

instructor/surveyConfirm.php
instructor/surveyResults.php

Using datatables to improve usability.

UsableResultsTables

---

fake_shibboleth.php

Fix_Developer_Login

---

backend/instructor/courseSurveysQueries.php
backend/instructor/lib/courseQueries.php

fix getSurveysFromSingleCourses + make courseSurveysQueries.php return empty values for keys if there is no data

rebase file structure and fix bugs 

---

db_creation_files/phpDummyData.sql

Since our new features relies on data of past courses, current courses, and surveys for both, I added more data for those to test them.

Adding more course and survey dummy data to phpDummyData.sql

---

backend/instructor/resultsDownload.php
backend/instructor/resultsView.php

Switched code to use the more logical POST request.

Switched to POST request since data is being sent

---

backend/instructor/deleteSurvey.php

Sprint3 73 delete survey

---

react-frontend/.env
react-frontend/src/Components/Course.jsx
react-frontend/src/styles/modal.css

Sprint3 survey adjustments

---

package-lock.json
react-frontend/.env
react-frontend/src/Components/Course.jsx

Merging survey cleanup to dev,

Survey Cleanup and Styling. Added Error mes to EXT

---

backend/instructor/lib/pairingFunctions.php
react-frontend/src/Components/Course.jsx

merged branch to dev, this branch includes changes to pairingFunctions.php which allows pairingMode db values to be updated.

added an extra if statement to deal with adding value in database pairing mode to handle more pairingmodes

---

backend/instructor/studentSurveyVisitData.php
db_creation_files/student_visit_data_table.sql
db_creation_files/survey_Types_Pairing_Mode.sql
documentation/RunningStudentSurveyLocally/Setting up StudentSurvey locally.md

mergedStudentVisitData branch along with some onboarding data

merged Student Visit Data branch and onboarding data branch

---

backend/instructor/studentSurveyVisitData.php
backend/unified_fake_Shibboleth.php

merged to dev with uncommented csrf token functinoality

uncommentd out csrf token functionalty.

---

backend/instructor/studentFillOutData.php
backend/instructor/studentSurveyVisitData.php
backend/unified_fake_Shibboleth.php

merging student completition check to dev

changed the return json to show survey id of associated survey rather then survye name

---

backend/instructor/courseSurveysQueries.php

technicalDebt

---

backend/lib/surveyQueries.php

technicalDebt2

---

backend/instructor/studentFillOutData.php

technicalDebt4

---

backend/lib/constants.php
react-frontend/.env
react-frontend/package.json

Final set of changes for release

BeatlesReleasePrep
